version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: >
      sh -c "python manage.py wait_for_db && 
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=myestate
      - DB_USER=myestate
      - DB_PASS=OOIIEGONJMRSQ2015
    depends_on: 
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=myestate
      - POSTGRES_USER=myestate
      - POSTGRES_PASSWORD=OOIIEGONJMRSQ2015