# Generated by Django 3.0.7 on 2020-06-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200625_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
