# Generated by Django 3.0.7 on 2020-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_block_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transction_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transction_type',
        ),
        migrations.RemoveField(
            model_name='registerurl',
            name='validated',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='registerurl',
            name='validation',
            field=models.URLField(default='https://api.tauridynamics.com/api/v1/payments/validation'),
            preserve_default=False,
        ),
    ]
